### ISSUE TITLE
Lists of UK school

### ISSUE THREAD

**Issue by hshahwan** [FACG5/unicornz#139]
In Sign up page, we will update the school names.
@Ollieblue Hi Marie, I will be great if you send a list of UK school to add in the database :)

**Comment by Ollieblue** [comment]
Hi @hshahwan here is a list of all UK schools https://get-information-schools.service.gov.uk/Establishments/Search?SelectedTab=Establishments&SearchType=EstablishmentAll&OpenOnly=true&TextSearchModel.AutoSuggestValue=&f=true&b=1&b=4
As there are so many, we cannot do a drop down list - maybe we have to type 3 - 4 characters so that a shorter list of schools starts to come up
If we do that, we should instruct the user to type in the first 4 letters....
